import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const helveticaNeue = localFont({
  src: [
    {
      path: '../public/fonts/HelveticaNeueRoman.woff2',
      weight: '400',
      style: 'normal'
    },
  ],
  variable: "--font-helvetica-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
